import re
from collections import defaultdict
from g2p_en import G2p


# Your phoneme inventory
LOGIT_TO_PHONEME = [
    "BLANK",
    "AA", "AE", "AH", "AO", "AW",
    "AY", "B", "CH", "D", "DH",
    "EH", "ER", "EY", "F", "G",
    "HH", "IH", "IY", "JH", "K",
    "L", "M", "N", "NG", "OW",
    "OY", "P", "R", "S", "SH",
    "T", "TH", "UH", "UW", "V",
    "W", "Y", "Z", "ZH",
    "|",
]
PHONEME_SET = set(LOGIT_TO_PHONEME) - {"BLANK"}
_word_re = re.compile(r"[A-Za-z']+")

_stress_tail = re.compile(r"[0-2]$")   # remove only trailing stress
_caps = re.compile(r"^[A-Z]+$")


def sentence_to_phonemes(text, g2p_instance=None):
    if g2p_instance is None:
        g2p_instance = G2p()

    # If you have your own remove_punctuation, keep using it
    # Otherwise this is a simple replacement
    text = re.sub(r"[^A-Za-z0-9'\s]", " ", text)

    phonemes = []
    if len(text.strip()) == 0:
        return ["|"], text

    for p in g2p_instance(text):
        if p == " ":
            if len(phonemes) == 0 or phonemes[-1] != "|":
                phonemes.append("|")
            continue

        p = p.strip()
        if not p:
            continue

        p = _stress_tail.sub("", p)

        if _caps.fullmatch(p) and p in PHONEME_SET:
            phonemes.append(p)

    if len(phonemes) == 0 or phonemes[-1] != "|":
        phonemes.append("|")

    # collapse repeated |
    compact = []
    for t in phonemes:
        if t == "|" and compact and compact[-1] == "|":
            continue
        compact.append(t)

    return compact, text


def build_lexicon_from_sentences(sentences, out_lexicon_path, lowercase=True):
    """
    Creates lexicon.txt with format:
      word PH1 PH2 PH3 ...
    Pronunciations are generated by the same G2p based pipeline used in your training.
    """
    g2p = G2p()
    lex = defaultdict(set)

    for s in sentences:
        for w in _word_re.findall(s):
            w_norm = w.lower() if lowercase else w

            phs, _ = sentence_to_phonemes(w_norm, g2p_instance=g2p)

            # remove word boundary tokens
            phs = [p for p in phs if p != "|"]

            # skip empty or invalid
            if not phs:
                continue
            if any(p not in PHONEME_SET or p == "|" for p in phs):
                continue

            lex[w_norm].add(" ".join(phs))

    with open(out_lexicon_path, "w", encoding="utf-8") as f:
        for w in sorted(lex.keys()):
            for pron in sorted(lex[w]):
                f.write(w + " " + pron + "\n")

    print("words:", len(lex))
    print("entries:", sum(len(v) for v in lex.values()))


def build_lexicon_from_wordlist(word_list, out_lexicon_path, lowercase=True):
    g2p = G2p()
    lex = defaultdict(set)

    for w in word_list:
        w_norm = w.lower() if lowercase else w

        phs, _ = sentence_to_phonemes(w_norm, g2p_instance=g2p)
        phs = [p for p in phs if p != "|"]

        if not phs:
            continue
        if any(p not in PHONEME_SET or p == "|" for p in phs):
            continue

        lex[w_norm].add(" ".join(phs))

    with open(out_lexicon_path, "w", encoding="utf-8") as f:
        for w in sorted(lex.keys()):
            for pron in sorted(lex[w]):
                f.write(w + " " + pron + "\n")

    print("words:", len(lex))
    print("entries:", sum(len(v) for v in lex.values()))




def load_word_list_from_dict_corpus(path):
    words = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            w = "".join(line.split()).lower()
            words.append(w)
    words = sorted(set(words))
    return words

word_list = load_word_list_from_dict_corpus("data/dict_corpus.txt")
build_lexicon_from_wordlist(word_list, "data/lexicon.txt")